import ftn.sbnz.banhammer.model.MatchEvent;
import ftn.sbnz.banhammer.model.MatchInfo;
import ftn.sbnz.banhammer.model.Punishment;
import ftn.sbnz.banhammer.model.ThreatLevel;
import ftn.sbnz.banhammer.model.Report;
import ftn.sbnz.banhammer.model.User;
import ftn.sbnz.banhammer.model.ChatLogAnalyzer;
import ftn.sbnz.banhammer.model.MatchHistory;

declare AnalyzeChatLog
    forWhat: String
end

declare PunishPlayer
    forWhat: String
end

declare IncreaseThreat end

rule "Match played with player reported for hate speech and any report in match history"
    when
        $match: MatchEvent($info: matchInfo, $info.report == Report.HATE_SPEECH, $info.finished == true)
        $u: User()
        MatchHistory($history: history)
        MatchInfo(report != Report.NONE) from $history
        not AnalyzeChatLog(forWhat == "hate")
    then
        System.out.println("HATE REPORT - REPORT IN MATCH HISTORY");
        System.out.println("PERFORMING ANALYSIS FOR HATE FOR " + $u.username);
        insert(new AnalyzeChatLog("hate"));
end

rule "Chat log analysis for hate true"
    when
        AnalyzeChatLog(forWhat == "hate")
        ChatLogAnalyzer(hate == true)
        $u: User()
    then
        System.out.println("ANALYSIS FOR HATE IS TRUE FOR " + $u.username);
        insert(new PunishPlayer("hate"));
end

rule "Chat log analysis for hate false"
    when
        AnalyzeChatLog(forWhat == "hate")
        ChatLogAnalyzer(hate == false)
        $u: User()
    then
        System.out.println("ANALYSIS FOR HATE IS FALSE FOR " + $u.username);
        $u.setPunishment(Punishment.NONE);
        insert($u);
        drools.halt();
end

rule "Punish for hate threat none"
    when
        PunishPlayer(forWhat == "hate")
        $u: User(threatLevel == ThreatLevel.NONE)
    then
        System.out.println("ISSUING 7 DAY SUSPENSION FOR " + $u.username + " FOR HATE");
        $u.setPunishment(Punishment.SUSPENSION_7_DAYS);
        update($u);
        insert(new IncreaseThreat());
end

rule "Punish for hate threat low"
    when
        PunishPlayer(forWhat == "hate")
        $u: User(threatLevel == ThreatLevel.LOW)
    then
        System.out.println("ISSUING PERMANENT SUSPENSION FOR " + $u.username + " FOR HATE");
        $u.setPunishment(Punishment.PERMANENT_SUSPENSION);
        update($u);
        insert(new IncreaseThreat());
end

rule "Punish for hate threat medium"
    when
        PunishPlayer(forWhat == "hate")
        $u: User(threatLevel == ThreatLevel.MEDIUM)
    then
        System.out.println("ISSUING PERMANENT SUSPENSION FOR " + $u.username + " FOR HATE");
        $u.setPunishment(Punishment.PERMANENT_SUSPENSION);
        update($u);
        insert(new IncreaseThreat());
end

rule "Punish for hate threat high"
    when
        PunishPlayer(forWhat == "hate")
        $u: User(threatLevel == ThreatLevel.HIGH)
    then
        System.out.println("ISSUING PERMANENT SUSPENSION FOR " + $u.username + " FOR HATE");
        $u.setPunishment(Punishment.PERMANENT_SUSPENSION);
        update($u);
        insert(new IncreaseThreat());
end