package sbnz.integracija;
import ftn.sbnz.banhammer.model.match.event.PlayerFlame;
import ftn.sbnz.banhammer.model.match.event.Ping;
import ftn.sbnz.banhammer.model.match.event.PlayerFriendlyFire
dialect  "mvel"

rule "Three pings and one player friendly fire"
salience 1
    when
        $fp: PlayerFriendlyFire($pfId: id, provoked == false, $matchId: matchId)
        $p1: Ping($pId: id, this before[1s, 3s] $fp, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not(PlayerFlame(this before[1s, 3s] $fp, this after[1s, 3s] $p1, matchId == $matchId))
        not(PlayerFriendlyFire(this before[1s, 3s] $fp, this after[1s, 3s] $p1, matchId == $matchId, id != $pfId))
    then
        System.out.println("Three pings and one player friendly fire");
        System.out.println();
        $fp.setProvoked(true);
        update($fp);
end

rule "Three pings and then one player flame"
salience 1
    when
        $fpl: PlayerFlame($fplId: id, provoked == false, $matchId: matchId)
        $p1: Ping($pId: id, this before[1s, 3s] $fpl, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not(PlayerFlame(this before[1s, 3s] $fpl, this after[1s, 3s] $p1, matchId == $matchId))
        not(PlayerFriendlyFire(this before[1s, 3s] $fpl, this after[1s, 3s] $p1, matchId == $matchId, id != $fplId))
    then
        System.out.println("Three pings and then one player flame");
        System.out.println();
        $fpl.setProvoked(true);
        update($fpl);
end

rule "Three pings and then one player flame and one player friendly fire"
salience 2
    when
        $fp: PlayerFriendlyFire($fpId: id, provoked == false, $matchId: matchId)
        $fpl: PlayerFlame($fplId: id, provoked == false, this before[1s, 3s] $fp, matchId == $matchId)
        $p1: Ping($pId: id, this before[1s, 3s] $fpl, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not(PlayerFlame(this before[1s, 3s] $fpl, this after[1s, 3s] $p1, matchId == $matchId, id != $fplId))
        not(PlayerFriendlyFire(this before[1s, 3s] $fpl, this after[1s, 3s] $p1, matchId == $matchId, id != $fpId))
    then
        System.out.println("Three pings and then one player flame and one player friendly fire");
        System.out.println();
        $fp.setProvoked(true);
        $fpl.setProvoked(true);
        update($fp);
        update($fpl);
end

rule "Three pings and then one player friendly fire and one player flame"
salience 2
    when
        $fpl: PlayerFlame($pfId: id, provoked == false, $matchId: matchId)
        $fp: PlayerFriendlyFire($pflId: id, provoked == false, this before[1s, 3s] $fpl, matchId == $matchId)
        $p1: Ping($pId: id, this before[1s, 3s] $fp, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not(PlayerFlame(this before[1s, 3s] $fp, this after[1s, 3s] $p1, matchId == $matchId, id != $pfId))
        not(PlayerFriendlyFire(this before[1s, 3s] $fp, this after[1s, 3s] $p1, matchId == $matchId, id != $pflId))
    then
        System.out.println("Three pings and then one player friendly fire and one player flame");
        System.out.println();
        $fp.setProvoked(true);
        $fpl.setProvoked(true);
        update($fp);
        update($fpl);
end

rule "Three ping and then two player friendly fire"
salience 2
    when
        $fp2: PlayerFriendlyFire($pf2Id: id, provoked == false, $matchId: matchId)
        $fp1: PlayerFriendlyFire($pf1Id: id, provoked == false, this before[1s, 3s] $fp2, matchId == $matchId, id != $pf2Id)
        $p1: Ping($pId: id, this before[1s, 3s] $fp1, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not PlayerFlame(this before[1s, 3s] $fp1, this after[1s, 3s] $p1, matchId == $matchId)
        not PlayerFriendlyFire(this after[1s, 3s] $p1, this before[1s, 3s] $fp1, matchId == $matchId, id != $pf1Id, id != $pf2Id)
    then
        System.out.println("Three ping and then two player friendly fire");
        System.out.println();
        $fp2.setProvoked(true);
        $fp1.setProvoked(true);
        update($fp2);
        update($fp1);
end

rule "Three ping and then two player flame"
salience 2
    when
        $fpl2: PlayerFlame($pf2Id: id, provoked == false, $matchId: matchId)
        $fpl1: PlayerFlame($pf1Id: id, provoked == false, this before[1s, 3s] $fpl2, matchId == $matchId, id != $pf2Id)
        $p1: Ping($pId: id, this before[1s, 3s] $fpl1, matchId == $matchId)
        $p2: Ping(this before[1s, 2s] $p1, matchId == $matchId)
        $p3: Ping(this before[1s, 2s] $p2, matchId == $matchId)
        not(PlayerFlame(this before[1s, 3s] $fpl1, this after[1s, 3s] $p1, matchId == $matchId, id != $pf1Id, id != $pf2Id))
        not(PlayerFriendlyFire(this before[1s, 3s] $fpl1, this after[1s, 3s] $p1, matchId == $matchId))
    then
        System.out.println("Two friendly fire and then two player flame");
        System.out.println();
        $fpl2.setProvoked(true);
        $fpl1.setProvoked(true);
        update($fpl2);
        update($fpl1);
end