package sbnz.integracija;
import ftn.sbnz.banhammer.model.Matches;
import ftn.sbnz.banhammer.model.MatchInfo;
import ftn.sbnz.banhammer.model.Punishment;

import java.lang.Math;
import java.util.List;


rule "WorstMatchesRule"
agenda-group "worst_matches"
salience ($punishmentScore * 20 + $kdScore + $finishedScore * (-10))
    when
        $match: MatchInfo($punishmentScore: punishment.ordinal(),
                          $kdScore: Math.round((1 / kdRatio) * 10),
                          $finishedScore: getFinishedInt())
        $worstMatches: Matches()
    then
        $worstMatches.matchesList.add($match);
        System.out.println("Worst matches " + $worstMatches.matchesList);
end